services:
  postgres-18:
    image: postgres:18
    container_name: pg18-volis-takehome
    # restart: always
    environment:
      POSTGRES_USER: api_user
      POSTGRES_PASSWORD: api_pass
      POSTGRES_DB: api_db
    ports:
      - "5432:5432"
    volumes:
      - pg18-api-data:/var/lib/postgresql

volumes:
  pg18-api-data:
